title: Lauro Silini
author: Lauro Silini

navbar-links:
  Research: "research"
  Teaching: "teaching"
  
  #Resources:
  #  - Beautiful Jekyll: "https://beautifuljekyll.com"
  #  - Learn markdown: "https://www.markdowntutorial.com/"
  #Author's home: "https://deanattali.com"

#avatar: avatar_old.png
#round-avatar: true
#social-network-links:
#  email: "someone@example.com"
title-on-all-pages: false 
#theme: jekyll-theme-minimal
remote_theme: daattali/beautiful-jekyll

page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"
