remote_theme: b2a3e8/jekyll-theme-console
description: "Personal homepage of Lauro Silini"
url: "https://laurosilini.github.io"
title: Lauro Silini

footer: Last update 16.09.2024

header_pages:
  - README.md
  - research.md
  - teaching.md
  - misc.md
  - contact.md

style: light
markdown: kramdown

