remote_theme: hitchens/patdryburgh
description: "Personal homepage of Lauro Silini"
url: "https://laurosilini.github.io"
title: Lauro Silini

footer: Last update 06.12.2024

header_pages:
  - README.md
  - research.md
  - teaching.md
  - misc.md
  - contact.md

style: light
markdown: kramdown

